import { marked } from 'marked';

document.addEventListener('DOMContentLoaded', () => {
    // 1. Element Selectors
    const chatForm = document.getElementById('chat-form');
    if (!chatForm) return;

    const chatMessages = document.getElementById('chat-messages');
    const userInput = document.getElementById('user-input');
    const sendBtn = document.getElementById('send-btn');
    const quickPromptBtns = document.querySelectorAll('.quick-prompt-btn');

    // 2. Configuration & State
    // Prefers data-endpoint attribute, falls back to /ai/chat
    const endpoint = chatForm.dataset.endpoint || '/ai/chat';
    
    // Automatically grabs token generated by @csrf inside the form
    const csrfToken = chatForm.querySelector('input[name="_token"]')?.value 
        || document.querySelector('meta[name="csrf-token"]')?.content;

    let conversationHistory = [];

    // 3. Helper: Append UI Messages
    function appendMessage(role, text) {
        const isUser = role === 'user';
        const msgDiv = document.createElement('div');
        msgDiv.className = `flex gap-3 text-sm ${isUser ? 'justify-end' : ''}`;

        let formattedContent;
        if (isUser) {
            // Escape HTML for user input security
            formattedContent = text.replace(/</g, "&lt;").replace(/>/g, "&gt;");
        } else {
            try {
                formattedContent = typeof marked !== 'undefined' ? marked.parse(text) : text;
            } catch (e) {
                formattedContent = text;
            }
        }

        const avatar = isUser
            ? `<div class="w-8 h-8 rounded-lg bg-indigo-600 text-white flex items-center justify-center font-bold text-xs shrink-0 shadow-xs">Vous</div>`
            : `<div class="w-8 h-8 rounded-lg bg-indigo-500 text-white flex items-center justify-center font-bold text-xs shrink-0 shadow-xs">IA</div>`;

        const bubbleClasses = isUser
            ? 'bg-indigo-600 text-white rounded-2xl rounded-tr-xs'
            : 'bg-slate-800 text-slate-100 rounded-2xl rounded-tl-xs border border-slate-700/60';

        msgDiv.innerHTML = `
            ${!isUser ? avatar : ''}
            <div class="${bubbleClasses} p-4 max-w-xl leading-relaxed prose prose-invert">
                ${formattedContent}
            </div>
            ${isUser ? avatar : ''}
        `;

        chatMessages.appendChild(msgDiv);
        chatMessages.scrollTop = chatMessages.scrollHeight;
    }

    // 4. Submit Event Listener
    chatForm.addEventListener('submit', async (e) => {
        // Prevent default HTML form GET/POST submission & page refresh
        e.preventDefault();
        e.stopPropagation();

        const text = userInput.value.trim();
        if (!text) return;

        // Update UI state
        appendMessage('user', text);
        conversationHistory.push({ role: 'user', content: text });
        userInput.value = '';
        sendBtn.disabled = true;

        // Render Loading Indicator
        const loadingDiv = document.createElement('div');
        loadingDiv.id = 'loading-indicator';
        loadingDiv.className = 'flex gap-3 text-sm';
        loadingDiv.innerHTML = `
            <div class="w-8 h-8 rounded-lg bg-indigo-500 text-white flex items-center justify-center font-bold text-xs shrink-0 shadow-xs">IA</div>
            <div class="bg-slate-800 text-slate-400 rounded-2xl rounded-tl-xs p-4 text-xs italic flex items-center gap-2 border border-slate-700/60">
                <span class="animate-pulse">Analyse en cours...</span>
            </div>
        `;
        chatMessages.appendChild(loadingDiv);
        chatMessages.scrollTop = chatMessages.scrollHeight;

        // Execute AJAX POST Fetch
        try {
            const response = await fetch(endpoint, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Accept': 'application/json',
                    'X-CSRF-TOKEN': csrfToken,
                    'X-Requested-With': 'XMLHttpRequest'
                },
                body: JSON.stringify({ messages: conversationHistory })
            });

            const data = await response.json();
            document.getElementById('loading-indicator')?.remove();

            if (response.ok && data.reply) {
                appendMessage('assistant', data.reply);
                conversationHistory.push({ role: 'assistant', content: data.reply });
            } else {
                appendMessage('assistant', `⚠️ Erreur (${response.status}): ${data.message || data.error || 'Impossible de traiter la demande.'}`);
            }
        } catch (err) {
            document.getElementById('loading-indicator')?.remove();
            appendMessage('assistant', '⚠️ Connexion au serveur interrompue.');
            console.error('Chat AJAX Exception:', err);
        } finally {
            sendBtn.disabled = false;
        }
    });

    // 5. Quick Prompt Buttons Handler
    quickPromptBtns.forEach((btn) => {
        btn.addEventListener('click', () => {
            const prompt = btn.dataset.prompt;
            if (prompt) {
                userInput.value = prompt;
                chatForm.dispatchEvent(new Event('submit', { cancelable: true, bubbles: true }));
            }
        });
    });
});
//proudct filter
document.addEventListener('DOMContentLoaded', () => {
    const filterForm = document.getElementById('product-filter-form');

    if (filterForm) {
        filterForm.addEventListener('submit', (e) => {
            const minInput = document.getElementById('min_price_input');
            const maxInput = document.getElementById('max_price_input');
            const errorEl = document.getElementById('price_error');

            if (!minInput || !maxInput || !errorEl) return;

            const minVal = parseFloat(minInput.value);
            const maxVal = parseFloat(maxInput.value);

            // Reset state
            errorEl.classList.add('hidden');
            errorEl.textContent = '';
            minInput.classList.remove('border-red-500');
            maxInput.classList.remove('border-red-500');

            // Min > Max validation
            if (!isNaN(minVal) && !isNaN(maxVal) && minVal > maxVal) {
                e.preventDefault();
                errorEl.textContent = 'Min price cannot be greater than Max price.';
                errorEl.classList.remove('hidden');
                minInput.classList.add('border-red-500');
                maxInput.classList.add('border-red-500');
                return false;
            }

            // Negative numbers validation
            if ((!isNaN(minVal) && minVal < 0) || (!isNaN(maxVal) && maxVal < 0)) {
                e.preventDefault();
                errorEl.textContent = 'Price cannot be negative.';
                errorEl.classList.remove('hidden');
                return false;
            }
        });
    }
});
// resources/js/app.js

document.addEventListener('DOMContentLoaded', function () {
    const searchInput = document.getElementById('product-search-input');
    
    // Safety check: Exit if not on the Create Sale page
    if (!searchInput) return;

    const searchResults = document.getElementById('search-results-dropdown');
    const cartRows = document.getElementById('cart-rows');
    const emptyCartMsg = document.getElementById('empty-cart-msg');
    const stockWarning = document.getElementById('stock-warning');
    const subtotalEl = document.getElementById('summary-subtotal');
    const remainingEl = document.getElementById('summary-remaining');
    const amountPaidInput = document.getElementById('amount_paid');

    let cart = {};
    let debounceTimer;

    // Live Search Handler
    searchInput.addEventListener('input', function () {
        clearTimeout(debounceTimer);
        const query = this.value.trim();

        if (query.length < 1) {
            searchResults.classList.add('hidden');
            return;
        }

        debounceTimer = setTimeout(() => {
            fetch(`/api/products/search?q=${encodeURIComponent(query)}`)
                .then(res => res.json())
                .then(products => {
                    searchResults.innerHTML = '';

                    if (products.length === 0) {
                        searchResults.innerHTML = `<div class="p-3 text-xs text-gray-500 text-center">No products found</div>`;
                    } else {
                        products.forEach(product => {
                            const item = document.createElement('div');
                            item.className = 'p-3 hover:bg-indigo-50 cursor-pointer flex justify-between items-center transition';
                            item.innerHTML = `
                                <div>
                                    <p class="font-bold text-gray-900 text-sm">${product.name}</p>
                                    <p class="text-xs text-gray-500">Stock: ${product.stock}</p>
                                </div>
                                <span class="font-extrabold text-indigo-600 text-sm">${parseFloat(product.price).toFixed(2)} TND</span>
                            `;
                            item.addEventListener('click', () => {
                                addProductToCart(product);
                                searchResults.classList.add('hidden');
                                searchInput.value = '';
                            });
                            searchResults.appendChild(item);
                        });
                    }
                    searchResults.classList.remove('hidden');
                });
        }, 250);
    });

    // Close dropdown when clicking outside
    document.addEventListener('click', function (e) {
        if (!searchInput.contains(e.target) && !searchResults.contains(e.target)) {
            searchResults.classList.add('hidden');
        }
    });

    function addProductToCart(product) {
        stockWarning.classList.add('hidden');

        if (cart[product.id]) {
            if (cart[product.id].quantity + 1 > product.stock) {
                showWarning(`Insufficient stock. Available: ${product.stock}`);
                return;
            }
            cart[product.id].quantity++;
        } else {
            if (product.stock < 1) {
                showWarning(`Insufficient stock. Available: 0`);
                return;
            }
            cart[product.id] = {
                id: product.id,
                name: product.name,
                price: parseFloat(product.price),
                stock: product.stock,
                quantity: 1
            };
        }
        renderCart();
    }

    function showWarning(msg) {
        stockWarning.innerText = msg;
        stockWarning.classList.remove('hidden');
    }

    function renderCart() {
        const keys = Object.keys(cart);

        if (keys.length === 0) {
            emptyCartMsg.classList.remove('hidden');
            cartRows.innerHTML = '';
            cartRows.appendChild(emptyCartMsg);
            updateTotals();
            return;
        }

        emptyCartMsg.classList.add('hidden');
        cartRows.innerHTML = '';

        keys.forEach(id => {
            const item = cart[id];
            const tr = document.createElement('tr');
            tr.className = 'hover:bg-gray-50';
            tr.innerHTML = `
                <td class="px-4 py-3 font-semibold text-gray-900">
                    ${item.name}
                    <input type="hidden" name="items[${id}][product_id]" value="${item.id}">
                </td>
                <td class="px-4 py-3 text-center">
                    <input type="number" min="1" max="${item.stock}" name="items[${id}][quantity]" value="${item.quantity}"
                        class="cart-qty-input w-20 text-center border-gray-300 rounded-md p-1 font-bold text-sm" data-id="${id}">
                </td>
                <td class="px-4 py-3 text-right text-gray-600">
                    ${item.price.toFixed(2)}
                    <input type="hidden" name="items[${id}][unit_price]" value="${item.price}">
                </td>
                <td class="px-4 py-3 text-right font-bold text-gray-900">
                    ${(item.price * item.quantity).toFixed(2)}
                </td>
                <td class="px-4 py-3 text-center">
                    <button type="button" class="remove-item text-red-500 hover:text-red-700 font-bold" data-id="${id}">✕</button>
                </td>
            `;
            cartRows.appendChild(tr);
        });

        document.querySelectorAll('.cart-qty-input').forEach(input => {
            input.addEventListener('change', function () {
                const id = this.dataset.id;
                let val = parseInt(this.value) || 1;

                if (val > cart[id].stock) {
                    showWarning(`Insufficient stock. Available: ${cart[id].stock}`);
                    val = cart[id].stock;
                    this.value = val;
                } else {
                    stockWarning.classList.add('hidden');
                }

                cart[id].quantity = val;
                renderCart();
            });
        });

        document.querySelectorAll('.remove-item').forEach(btn => {
            btn.addEventListener('click', function () {
                delete cart[this.dataset.id];
                renderCart();
            });
        });

        updateTotals();
    }

    function updateTotals() {
        let subtotal = 0;
        Object.values(cart).forEach(item => {
            subtotal += item.price * item.quantity;
        });

        subtotalEl.innerText = subtotal.toFixed(2);
        
        const paid = parseFloat(amountPaidInput.value) || 0;
        const remaining = Math.max(0, subtotal - paid);
        remainingEl.innerText = remaining.toFixed(2);
    }

    if (amountPaidInput) {
        amountPaidInput.addEventListener('input', updateTotals);
    }
});