import { marked } from 'marked';

document.addEventListener('DOMContentLoaded', () => {
    // 1. Element Selectors
    const chatForm = document.getElementById('chat-form');
    if (!chatForm) return;

    const chatMessages = document.getElementById('chat-messages');
    const userInput = document.getElementById('user-input');
    const sendBtn = document.getElementById('send-btn');
    const quickPromptBtns = document.querySelectorAll('.quick-prompt-btn');

    // 2. Configuration & State
    // Prefers data-endpoint attribute, falls back to /ai/chat
    const endpoint = chatForm.dataset.endpoint || '/ai/chat';
    
    // Automatically grabs token generated by @csrf inside the form
    const csrfToken = chatForm.querySelector('input[name="_token"]')?.value 
        || document.querySelector('meta[name="csrf-token"]')?.content;

    let conversationHistory = [];

    // 3. Helper: Append UI Messages
    function appendMessage(role, text) {
        const isUser = role === 'user';
        const msgDiv = document.createElement('div');
        msgDiv.className = `flex gap-3 text-sm ${isUser ? 'justify-end' : ''}`;

        let formattedContent;
        if (isUser) {
            // Escape HTML for user input security
            formattedContent = text.replace(/</g, "&lt;").replace(/>/g, "&gt;");
        } else {
            try {
                formattedContent = typeof marked !== 'undefined' ? marked.parse(text) : text;
            } catch (e) {
                formattedContent = text;
            }
        }

        const avatar = isUser
            ? `<div class="w-8 h-8 rounded-lg bg-indigo-600 text-white flex items-center justify-center font-bold text-xs shrink-0 shadow-xs">Vous</div>`
            : `<div class="w-8 h-8 rounded-lg bg-indigo-500 text-white flex items-center justify-center font-bold text-xs shrink-0 shadow-xs">IA</div>`;

        const bubbleClasses = isUser
            ? 'bg-indigo-600 text-white rounded-2xl rounded-tr-xs'
            : 'bg-slate-800 text-slate-100 rounded-2xl rounded-tl-xs border border-slate-700/60';

        msgDiv.innerHTML = `
            ${!isUser ? avatar : ''}
            <div class="${bubbleClasses} p-4 max-w-xl leading-relaxed prose prose-invert">
                ${formattedContent}
            </div>
            ${isUser ? avatar : ''}
        `;

        chatMessages.appendChild(msgDiv);
        chatMessages.scrollTop = chatMessages.scrollHeight;
    }

    // 4. Submit Event Listener
    chatForm.addEventListener('submit', async (e) => {
        // Prevent default HTML form GET/POST submission & page refresh
        e.preventDefault();
        e.stopPropagation();

        const text = userInput.value.trim();
        if (!text) return;

        // Update UI state
        appendMessage('user', text);
        conversationHistory.push({ role: 'user', content: text });
        userInput.value = '';
        sendBtn.disabled = true;

        // Render Loading Indicator
        const loadingDiv = document.createElement('div');
        loadingDiv.id = 'loading-indicator';
        loadingDiv.className = 'flex gap-3 text-sm';
        loadingDiv.innerHTML = `
            <div class="w-8 h-8 rounded-lg bg-indigo-500 text-white flex items-center justify-center font-bold text-xs shrink-0 shadow-xs">IA</div>
            <div class="bg-slate-800 text-slate-400 rounded-2xl rounded-tl-xs p-4 text-xs italic flex items-center gap-2 border border-slate-700/60">
                <span class="animate-pulse">Analyse en cours...</span>
            </div>
        `;
        chatMessages.appendChild(loadingDiv);
        chatMessages.scrollTop = chatMessages.scrollHeight;

        // Execute AJAX POST Fetch
        try {
            const response = await fetch(endpoint, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Accept': 'application/json',
                    'X-CSRF-TOKEN': csrfToken,
                    'X-Requested-With': 'XMLHttpRequest'
                },
                body: JSON.stringify({ messages: conversationHistory })
            });

            const data = await response.json();
            document.getElementById('loading-indicator')?.remove();

            if (response.ok && data.reply) {
                appendMessage('assistant', data.reply);
                conversationHistory.push({ role: 'assistant', content: data.reply });
            } else {
                appendMessage('assistant', `⚠️ Erreur (${response.status}): ${data.message || data.error || 'Impossible de traiter la demande.'}`);
            }
        } catch (err) {
            document.getElementById('loading-indicator')?.remove();
            appendMessage('assistant', '⚠️ Connexion au serveur interrompue.');
            console.error('Chat AJAX Exception:', err);
        } finally {
            sendBtn.disabled = false;
        }
    });

    // 5. Quick Prompt Buttons Handler
    quickPromptBtns.forEach((btn) => {
        btn.addEventListener('click', () => {
            const prompt = btn.dataset.prompt;
            if (prompt) {
                userInput.value = prompt;
                chatForm.dispatchEvent(new Event('submit', { cancelable: true, bubbles: true }));
            }
        });
    });
});